Document: decklink-debugger
Title: Debian decklink-debugger Manual
Author: <insert document author here>
Abstract: This manual describes what decklink-debugger is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/decklink-debugger/decklink-debugger.sgml.gz

Format: postscript
Files: /usr/share/doc/decklink-debugger/decklink-debugger.ps.gz

Format: text
Files: /usr/share/doc/decklink-debugger/decklink-debugger.text.gz

Format: HTML
Index: /usr/share/doc/decklink-debugger/html/index.html
Files: /usr/share/doc/decklink-debugger/html/*.html
